version: "3.9"
services:
  go-backend:
    container_name: "go-crud"
    image: "go-crud"
    build:
      context: . 
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - linov-go
  postgres:
    image: postgres:13-alpine
    container_name: "postgres-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_crud_db
    ports:
      - "6666:5432"
    networks:
      - linov-go

networks:
  linov-go:
    external: true
